SELECT ITEMID, SUM(SOLDCOUNT) AS TOTALCOUNT FROM USERS
JOIN
(SELECT USERID, ITEMID, SUM(QUANTITY) SOLDCOUNT 
FROM ORDERS A JOIN ORDERDETAILS B
ON A.ORDERID = B.ORDERID
GROUP BY USERID, ITEMID) A
ON USERS.USERID = A. USERID
WHERE GENDER = 'M'
GROUP BY ITEMID
ORDER BY TOTALCOUNT DESC;